language: php
php:
    - 5.5
    - 5.6
before_script:
  - mysql -e 'create database wow;'
  - cd api && composer install --prefer-dist
  - cp -f api/app/config/parameters.yml.travis api/app/config/parameters.yml
  - cd api && app/console doctrine:database:create --env=test
  - cd api && app/console doctrine:schema:create --env=test
  - cd api && app/console doctrine:fixtures:load -n --env=test
script:
 - cd api && phpunit -c app
