language: php
php:
    - 5.5
    - 5.6
env:
    - SYMFONY_ENV="test"
before_script:
    - cd api
    - mysql -e 'create database wow;'
    - composer install --prefer-dist
    - cp -f app/config/parameters.yml.travis app/config/parameters.yml
    - app/console doctrine:database:create
    - app/console doctrine:schema:create
    - app/console doctrine:fixtures:load -n
script:
     - cd api && phpunit -c app
