language: php
php:
    - 5.5
    - 5.6

before_script:

  - cp api/app/config/parameters.yml.travis api/app/config/parameters.yml
  - cd api && composer install --prefer-dist
  - mysql -e 'create database wow;'
  - php api/app/console doctrine:database:create --env=test
  - php api/app/console doctrine:schema:create --env=test
  - php api/app/console doctrine:fixtures:load -n --env=test

script: cd api && phpunit -c app
