language: php
php:
    - 5.5
    - 5.6
    - hhvm
env:
    - SYMFONY_ENV="test"
before_script:
    - cd api
    - composer install --prefer-dist
    - cp -f app/config/parameters.yml.travis app/config/parameters.yml
    - php app/console doctrine:database:create
    - php app/console doctrine:schema:create
    - php app/console doctrine:fixtures:load -n
script:
     - phpunit -c app