maniadoge:
    type: rest
    resource: "@ManiadogeBundle/Resources/config/routing.yml"
    prefix:   /
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api

