maniadoge_index:
    path:     /
    defaults: { _controller: ManiadogeBundle:Doge:index }

maniadoge_doge:
    path:     /{id}
    defaults: { _controller: ManiadogeBundle:Doge:doge }
    
maniadoge_create:
    path:     /woof/woof/{name}/{imageUrl}
    defaults: { _controller: ManiadogeBundle:Doge:create }    
