maniadoge_index:
    path:     /
    defaults: { _controller: maniadoge.controllers.doge:index }
    
maniadoge_create:
    path:     /woof/woof/{name}/{imageUrl}
    defaults: { _controller: maniadoge.controllers.doge:create }    
