services:
    manialib.maniascript.autoloader:
        class: Manialib\Maniascript\Autoloader
        calls:
            - ['setLogger', [@logger]]
            
    manialib.maniascript.compiler:
        class: Manialib\Maniascript\Compiler
        arguments:
            - @manialib.maniascript.autoloader
        calls:
            - ['setLogger', [@logger]]