fos_rest:
    param_fetcher_listener: false
    body_listener: false
    format_listener:
        rules:
            # ConvertToHtmlResponse should be smarter...
            - { path: ^/doges/new, priorities: [ json, xml, html ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }

    view:
        view_response_listener: force
        templating_formats:
            html: true

nelmio_api_doc: ~