fos_rest:
    param_fetcher_listener: false
    body_listener: false
    format_listener:
        rules:
            - { path: ^/, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }
    view:
        view_response_listener: true
        templating_formats:
            html: false

nelmio_api_doc: ~