Nadeo\Live\ManiadogeBundle\Entity\Doge:
    type: entity
    repositoryClass: Nadeo\Live\ManiadogeBundle\Entity\DogeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '75'
            unique: true
        imageUrl:
            type: string
            length: 255
